# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Azure App - Build and Deploy

on:
  push:
    branches:
      - main
    paths-ignore:
      - .github/workflows/main_jps-tarot-api.yml
      - server/*
      - .editorconfig
      - .gitignore
      - notes.md
      - readme.md
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: npm install and build
        run: |
          npm install
          npm run build-prod --if-present
        working-directory: app

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: tarot-app
          path: ./app/dist/tarot

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: tarot-app

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'jps-tarot-app'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_AF1C1D922BB24328ABDD77DFB8B4BDC0 }}
          package: .
